"""TST-03 golden-master replay regression test.

Replays the ``acquire_scan`` signal sequence captured by
``test/golden/_record.py`` and asserts sequence equality against the
generated ``test/golden/default.json`` fixture (D-12). The fixture is
generated by ``_record.py`` only — never hand-edited — so a hand-edit
that masks a regression is caught at the next regeneration (the diff is
the behavioral change to review).

This is the KEY safety net for the Phase 5 god-object split: it captures
the ordered ``sig_message`` / ``sig_progress_update`` emission contract
at the signal level (not the source level), so a refactor that
re-sequences, adds, or drops an emission is caught even if the source
text changes beyond recognition.
"""

import json
import os

from test.golden._record import capture_acquisition_sequence

_FIXTURE = os.path.join(os.path.dirname(__file__), "golden", "default.json")


def test_golden_acquisition_default() -> None:
    """The default mock-acquisition signal sequence matches the golden fixture.

    The happy path (no DAQ error, no camera timeout) emits zero
    sig_message / sig_progress_update calls — the fixture is an empty
    list. This characterizes the contract: a successful acquisition is
    silent on the message channel. A refactor that introduces an
    emission on the happy path (e.g. a stray status update) is caught
    here.
    """
    with open(_FIXTURE, encoding="utf-8") as f:
        expected = json.load(f)
    actual = capture_acquisition_sequence("default")
    assert actual == expected, (
        "acquire_scan signal sequence diverged from the golden master. "
        "If this is an intentional behavioral change, regenerate the "
        "fixture with `uv run python test/golden/_record.py` and review "
        "the diff before committing."
    )
