"""TST-03 golden-master replay regression test.

Replays the ``acquire_scan`` signal sequence captured by
``test/golden/_record.py`` and asserts sequence equality against the
generated ``test/golden/*.json`` fixtures. The fixtures are generated by
``_record.py`` only — never hand-edited — so a hand-edit that masks a
regression is caught at the next regeneration (the diff is the behavioral
change to review).

This is the KEY safety net for the Phase 5 god-object split: it captures
the ordered ``sig_message`` / ``sig_progress_update`` emission contract
at the signal level (not the source level), so a refactor that
re-sequences, adds, or drops an emission is caught even if the source
text changes beyond recognition.

Two scenarios are replayed:

* ``default`` — the silent happy path (no DAQ error, no camera timeout).
  Emits zero ``sig_message`` / ``sig_progress_update`` calls; the fixture
  is an empty list. A refactor that introduces an emission on the happy
  path (e.g. a stray status update) is caught here.
* ``siggen_create_scanner_fail`` — the siggen ``create_scanner`` failure
  early-return path. Emits one ``sig_message`` ("Scan task creation
  failed ..."). Closes Pitfall 2 for this error path: a dropped or
  re-sequenced emission on the create-scanner failure branch is now
  catchable, not just the happy path.
* ``preview_auto_laser`` — the D-05 preview-auto-laser fold. Runs
  ``preview_mode_worker`` (not ``acquire_scan``) with a real
  ``HardwareManager`` backing the ``self._hw`` reference. On the happy
  path (MockLaser, no HAL error) the ``sig_message`` sequence is empty —
  the fold's ``start_lasers``/``stop_lasers`` calls introduced no stray
  emission on the message channel. This is the ONE scenario that
  differs from a hypothetical pre-split re-recording: before the fold,
  ``preview_mode_worker`` did not call ``start_lasers``/``stop_lasers``
  at all.
"""

import json
from pathlib import Path

import pytest

from test.golden._record import capture_acquisition_sequence

_GOLDEN_DIR = Path(__file__).resolve().parents[1] / "golden"

_SCENARIOS = [
    "default",
    "siggen_create_scanner_fail",
    "preview_auto_laser",
]


@pytest.mark.parametrize("scenario", _SCENARIOS)
def test_golden_acquisition(scenario: str) -> None:
    """The mock-acquisition signal sequence matches the golden fixture.

    Each scenario's fixture is regenerated only by
    ``uv run python test/golden/_record.py``. If this assertion fails,
    regenerate the fixture and review the diff before committing — a
    divergence is the behavioral change to audit, not a test bug.
    """
    fixture = _GOLDEN_DIR / f"{scenario}.json"
    with fixture.open(encoding="utf-8") as f:
        expected = json.load(f)
    actual = capture_acquisition_sequence(scenario)
    assert actual == expected, (
        f"acquire_scan signal sequence diverged from the golden master "
        f"for scenario {scenario!r}. If this is an intentional behavioral "
        f"change, regenerate the fixture with "
        f"`uv run python test/golden/_record.py` and review the diff "
        f"before committing."
    )
