"""Golden-master capture harness for the acquire_scan signal sequence.

This module is the SOLE regeneration path for ``test/golden/default.json``
(D-12). The fixture is generated by running::

    uv run python test/golden/_record.py

and is committed to the repo. It must NOT be hand-edited — a hand-edit
would mask the exact regression this safety net exists to catch. The
replay test ``test/test_golden_acquisition.py`` asserts
``capture_acquisition_sequence("default") == json.load(default.json)``;
regenerating the fixture after a refactor produces a diff that is the
behavioral change to review.

Determinism sources (EDGE — flagged-unverified assumption, documented here
so the safety net's integrity is auditable):

* ``MockSigGen`` reuses the pure-numpy ``lightsheet.waveforms`` generators
  with hardcoded synthetic config defaults (sample_rate=40000, etc.) — no
  config.ini read, no hardware, no random seed. The same inputs always
  produce bit-identical waveform arrays.
* ``MockCamera`` returns ``np.zeros((n, ysize, xsize), dtype=uint16)``
  canned frames — deterministic shape and content.
* ``MockMotors`` / ``MockETLs`` / ``MockLaser`` track state in plain
  instance attributes with no I/O.

The harness execs the REAL ``Controller_MainWindow.acquire_scan`` body
(via the ``_load_method`` exec-against-Mock pattern from
``test/test_laser_controls.py``) against a Mock stand-in ``self`` whose
HAL attributes are the six ``Mock*`` classes. This runs the real method
source — the same code that runs on the rig — without needing a Qt event
loop or a display (RESEARCH.md §Standard Stack: no pytest-qt). The
ordered ``sig_message.emit`` / ``sig_progress_update.emit`` call sequence
is captured as a JSON list of ``{"type": ..., "value": ...}`` dicts.

``acquire_scan`` references module-level names (``datetime``, ``logger``,
``np``) from ``lightsheet/gui/controller.py``; the exec namespace is
seeded with them so the body resolves them at call time.
"""

import datetime
import json
import logging
import os
import re
from collections.abc import Callable
from typing import Any
from unittest.mock import Mock

import numpy as np

from lightsheet.hal import (
    MockCamera,
    MockETLs,
    MockLaser,
    MockMotors,
    MockSigGen,
)

_CONTROLLER_SRC = os.path.join(
    os.path.dirname(__file__), "..", "..", "lightsheet", "gui", "controller.py"
)

# Module-level logger the exec'd body references (controller.py:45).
_logger = logging.getLogger("lightsheet.gui.controller")


def _read_controller_source() -> str:
    with open(_CONTROLLER_SRC) as f:
        return f.read()


def _slice_method(src: str, method_sig: str) -> str:
    """Return the body of a method, from its ``def <sig>:`` line up to the
    next top-level ``def``/``@pyqtSlot`` decorator."""
    m = re.search(r"def " + re.escape(method_sig) + r":", src)
    assert m, f"{method_sig} is missing"
    body = src[m.start() :]
    end = re.search(r"\n    def |\n    @pyqtSlot", body[1:])
    if end:
        body = body[: end.start() + 1]
    return body


def _load_method(method_sig: str) -> Callable[..., Any]:
    """Extract a method body from controller.py and return a callable.

    The exec namespace is seeded with the module-level names the body
    references (``datetime``, ``logger``, ``np``) so the function resolves
    them at call time via its ``__globals__``.
    """
    src = _read_controller_source()
    body = _slice_method(src, method_sig)
    namespace: dict[str, Any] = {
        "datetime": datetime,
        "logger": _logger,
        "np": np,
    }
    exec(compile(body, _CONTROLLER_SRC, "exec"), namespace)
    func_name = method_sig.split("(")[0].strip()
    return namespace[func_name]


def _build_standin() -> Mock:
    """Build the Mock stand-in ``self`` for acquire_scan.

    Wires the six Mock* HAL classes plus the UI widgets and attributes
    acquire_scan reads. The siggen's waveforms are pre-computed so
    ``waveform_cycles`` / ``waveform_metadata`` are populated (the real
    controller calls ``compute_scan_waveforms`` before ``acquire_scan``).
    """
    camera = MockCamera()
    siggen = MockSigGen(camera)
    siggen.compute_scan_waveforms()

    standin = Mock()
    standin.camera = camera
    standin.siggen = siggen
    standin.motors = MockMotors()
    # The controller holds list[ILaser] (Wave 3 rewrite). acquire_scan does
    # not reference self.lasers, but the stand-in mirrors hardware_init's
    # shape so a future body change that does read laser state is caught.
    standin.lasers = [
        MockLaser(wavelength=555, max_power_mw=300.0, label="Laser 1 (555 nm)"),
        MockLaser(wavelength=640, max_power_mw=150.0, label="Laser 2 (640 nm)"),
    ]
    standin.etls = MockETLs()

    # Signal mocks — emit calls are captured via call_args_list.
    standin.sig_message = Mock()
    standin.sig_progress_update = Mock()

    # UI widgets acquire_scan reads.
    standin.ui.lineEdit_saveDescription.text.return_value = "sample"
    standin.ui.checkBox_saveStitchBlend.isChecked.return_value = False

    # frame_viewer.enqueue_frame receives the reconstructed frame.
    standin.frame_viewer = Mock()

    return standin


def capture_acquisition_sequence(scenario: str) -> list[dict]:
    """Run the real acquire_scan body against a Mock stand-in and return
    the ordered ``sig_message`` / ``sig_progress_update`` emit sequence.

    ``scenario`` selects the fixture name (only "default" is defined
    today). The sequence is a list of ``{"type": "sig_message" |
    "sig_progress", "value": <first positional arg>}`` dicts in emission
    order.
    """
    if scenario != "default":
        raise ValueError(f"unknown scenario: {scenario!r}")
    standin = _build_standin()
    acquire_scan = _load_method("acquire_scan(self) -> None")
    acquire_scan(standin)

    sequence: list[dict] = []
    for call in standin.sig_message.emit.call_args_list:
        sequence.append({"type": "sig_message", "value": call.args[0]})
    for call in standin.sig_progress_update.emit.call_args_list:
        sequence.append({"type": "sig_progress", "value": call.args[0]})
    return sequence


def record_acquisition(out_path: str) -> None:
    """Capture the default scenario and write it to ``out_path`` as JSON."""
    seq = capture_acquisition_sequence("default")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(seq, f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "default.json")
    record_acquisition(out)
    print(f"Wrote {out}")
