"""Golden-master capture harness for the acquire_scan signal sequence.

This module is the SOLE regeneration path for ``test/golden/default.json``
(D-12). The fixture is generated by running::

    uv run python test/golden/_record.py

and is committed to the repo. It must NOT be hand-edited — a hand-edit
would mask the exact regression this safety net exists to catch. The
replay test ``test/test_golden_acquisition.py`` asserts
``capture_acquisition_sequence("default") == json.load(default.json)``;
regenerating the fixture after a refactor produces a diff that is the
behavioral change to review.

Determinism sources (EDGE — flagged-unverified assumption, documented here
so the safety net's integrity is auditable):

* ``MockSigGen`` reuses the pure-numpy ``lightsheet.waveforms`` generators
  with hardcoded synthetic config defaults (sample_rate=40000, etc.) — no
  config.ini read, no hardware, no random seed. The same inputs always
  produce bit-identical waveform arrays.
* ``MockCamera`` returns ``np.zeros((n, ysize, xsize), dtype=uint16)``
  canned frames — deterministic shape and content.
* ``MockMotors`` / ``MockETLs`` / ``MockLaser`` track state in plain
  instance attributes with no I/O.

The harness execs the REAL ``_AcquireScanMixin.acquire_scan`` body
(via the ``_load_method`` exec-against-Mock pattern from
``test/test_laser_controls.py``) against a Mock stand-in ``self`` whose
HAL attributes are the six ``Mock*`` classes. This runs the real method
source — the same code that runs on the rig — without needing a Qt event
loop or a display (RESEARCH.md §Standard Stack: no pytest-qt). The
ordered ``sig_message.emit`` / ``sig_progress_update.emit`` call sequence
is captured as a JSON list of ``{"type": ..., "value": ...}`` dicts.

``acquire_scan`` now lives in ``lightsheet/gui/workers/scan_mixin.py`` and
references module-level names (``datetime``, ``logger``, ``np``) from
there; the exec namespace is seeded with them so the body resolves them
at call time.

Two further capture families widen the net beyond ``acquire_scan``:

* ``capture_stack_sequence`` execs the real ``StackWorker.run`` body
  (sliced from ``lightsheet/gui/workers/stack.py``) against a Mock
  stand-in and records ONE ordered call list — every ``sig_message`` /
  ``sig_progress_update`` / ``sig_beep`` emission plus the setup and
  teardown calls (``_fs.set_files``/``start_saving``/``stop_saving``,
  ``camera.arm_scan``/``disarm``, ``_hw.start_lasers``/``stop_lasers``,
  ``siggen.update_etls``, ``finished.emit``, ``pause_requested.clear``)
  — so the emission contract AND the cleanup ordering are both pinned.
  Every method ``run()`` invokes through ``self.`` is bound from the
  real ``StackWorker`` class via ``types.MethodType`` (``acquire_scan``
  is the one deliberate Mock — it has its own golden coverage), so a
  future in-file split of ``run()`` into phase helpers resolves to real
  bodies here instead of being swallowed by Mock auto-attrs.
* ``capture_manifest_lifecycle`` drives the REAL ``FrameSaver`` (no
  exec) with a minimal ``QObject`` shell stand-in and a tmp save
  directory, snapshotting the ``.resume.json`` sidecar after each
  lifecycle step (set_files -> staged updates -> cursor commit ->
  stop_saving finalize). Nondeterminism (UUIDs, timestamps, absolute
  paths, the safety-config fingerprint) is normalized before recording.
"""

import datetime
import inspect
import json
import logging
import re
import tempfile
import threading
import types
from collections.abc import Callable
from pathlib import Path
from typing import Any
from unittest.mock import Mock

import numpy as np
from PySide6.QtCore import QObject

import lightsheet.gui.workers.stack as _stack_mod
from lightsheet.gui.coordinators.frame_saver_controller import FrameSaver
from lightsheet.gui.coordinators.hardware_manager import HardwareManager
from lightsheet.gui.workers.stack import StackWorker
from lightsheet.hal import (
    DeviceBundle,
    MockCamera,
    MockETLs,
    MockLaser,
    MockMotors,
    MockSigGen,
)
from lightsheet.resume import ManifestUpdate

_HERE = Path(__file__).resolve().parent
_CONTROLLER_SRC = _HERE / ".." / ".." / "lightsheet" / "gui" / "controller.py"
_ACQ_SRC = _HERE / ".." / ".." / "lightsheet" / "gui" / "acquisition_coordinator.py"
_SCAN_MIXIN_SRC = (
    _HERE / ".." / ".." / "lightsheet" / "gui" / "workers" / "scan_mixin.py"
)
_PREVIEW_LIVE_SINGLE_SRC = (
    _HERE / ".." / ".." / "lightsheet" / "gui" / "workers" / "preview_live_single.py"
)
_STACK_SRC = (
    _HERE / ".." / ".." / "lightsheet" / "gui" / "workers" / "stack.py"
)

# Module-level logger the exec'd body references (controller.py:45).
_logger = logging.getLogger("lightsheet.gui.shell.controller")


def _read_controller_source() -> str:
    with Path(_CONTROLLER_SRC).open(encoding="utf-8") as f:
        return f.read()


def _slice_method(src: str, method_sig: str) -> str:
    """Return the body of a method, from its ``def <sig>:`` line up to the
    next top-level ``def``/``@Slot`` decorator or ``class`` boundary."""
    m = re.search(r"def " + re.escape(method_sig) + r":", src)
    assert m, f"{method_sig} is missing"
    body = src[m.start() :]
    end = re.search(r"\n    def |\n    @Slot|\nclass ", body[1:])
    if end:
        body = body[: end.start() + 1]
    return body


def _load_method(
    method_sig: str,
    src_path: str = str(_CONTROLLER_SRC),
    extra_ns: dict[str, Any] | None = None,
) -> Callable[..., Any]:
    """Extract a method body from the given source file and return a callable.

    Defaults to controller.py; pass ``_ACQ_SRC`` for ``acquire_scan`` (moved
    to ``AcquisitionCoordinator`` in the god-object split). The exec
    namespace is seeded with the module-level names the body references
    (``datetime``, ``logger``, ``np``) so the function resolves them at
    call time via its ``__globals__``. ``extra_ns`` merges additional
    names — pass ``dict(vars(<source module>))`` so the exec'd body
    resolves every module-level name exactly as production does.
    """
    with Path(src_path).open(encoding="utf-8") as f:
        src = f.read()
    body = _slice_method(src, method_sig)
    namespace: dict[str, Any] = {
        "datetime": datetime,
        "logger": _logger,
        "np": np,
    }
    if extra_ns:
        namespace.update(extra_ns)
    exec(compile(body, src_path, "exec"), namespace)
    func_name = method_sig.split("(")[0].strip()
    return namespace[func_name]


def _build_standin() -> Mock:
    """Build the Mock stand-in ``self`` for acquire_scan.

    acquire_scan now lives on ``_AcquireScanMixin`` in
    ``lightsheet/gui/workers/scan_mixin.py`` (relocated from AcquisitionCoordinator).
    The mixin reads its own ``self.camera`` / ``self.siggen`` /
    ``self.motors`` attributes, shell-owned state via ``self._shell.*``
    (``sig_message``, ``sig_progress_update``, ``_fs``,
    ``buffer`` / ``reconstructed_frame`` / ``buffer_metadata_*``), and
    the pre-sampled save options via ``self._save_description`` /
    ``self._save_stitch_blend`` (constructor args on the worker QObject,
    set directly on the stand-in here). The stand-in IS the worker
    (``self``); ``self._shell`` is a Mock exposing the shell-owned
    attributes acquire_scan reads. The siggen's waveforms are
    pre-computed so ``waveform_cycles`` / ``waveform_metadata`` are
    populated (the real worker calls ``compute_scan_waveforms`` before
    ``acquire_scan``).

    Regenerated fixtures matched the pre-migration fixtures byte-for-byte
    (same values, only the access path changed from shell UI widgets to
    instance attrs).
    """
    camera = MockCamera()
    siggen = MockSigGen(camera)
    siggen.compute_scan_waveforms()

    standin = Mock()
    # Worker's own HAL handles.
    standin.camera = camera
    standin.siggen = siggen
    standin.motors = MockMotors()
    # The worker holds list[ILaser] (Wave 3 rewrite). acquire_scan does
    # not reference self.lasers, but the stand-in mirrors hardware_init's
    # shape so a future body change that does read laser state is caught.
    standin.lasers = [
        MockLaser(wavelength=555, max_power_mw=300.0, label="Laser 1 (555 nm)"),
        MockLaser(wavelength=647, max_power_mw=150.0, label="Laser 2 (647 nm)"),
    ]
    standin.etls = MockETLs()

    # B-03: save options are now ctor args on the worker QObject, pre-sampled
    # on the GUI thread. The stand-in mirrors the worker's instance attrs
    # directly — acquire_scan reads self._save_description /
    # self._save_stitch_blend, NOT self._shell.ui.* widgets.
    standin._save_description = "sample"
    standin._save_stitch_blend = False

    # Shell reference — acquire_scan reads shell-owned state via self._shell.*
    shell = Mock()
    # Signal mocks — emit calls are captured via call_args_list.
    shell.sig_message = Mock()
    shell.sig_progress_update = Mock()
    # FrameSaverController enqueue_frame receives the reconstructed frame.
    shell._fs = Mock()
    # Frame-reconstruction helpers stay on the shell — acquire_scan calls
    # self._shell.reconstruct_frame(self._shell.buffer). Plain Mock
    # callables return Mock instances; the enqueue_frame capture is what
    # the golden replay asserts on (the emission sequence), not the frame
    # content.
    standin._shell = shell

    return standin


def _build_preview_standin() -> Mock:
    """Build the Mock stand-in ``self`` for ``PreviewWorker.run``.

    ``PreviewWorker`` lives in ``lightsheet/gui/workers/preview_live_single.py``
    (relocated from ``AcquisitionCoordinator.preview_mode_worker`` as the first step
    of the threading-vehicle migration) and reads its own ``self.camera``
    attribute plus shell-owned state via ``self._shell.*``
    (``preview_mode_started``, ``estop_event``, ``_fs``,
    ``sig_message``) and laser control via ``self._hw`` (the
    ``start_lasers``/``stop_lasers`` calls). The stand-in IS the worker
    (``self``); ``self._hw`` is a real ``HardwareManager`` backed by a
    ``DeviceBundle`` of Mock devices so the laser start/stop calls
    exercise the real ``HardwareManager.start_lasers``/``stop_lasers``
    path (which emits ``sig_message`` only on a HAL error — MockLaser
    does not error, so the happy-path fixture is an empty list, proving
    the relocation introduced no stray emission on the message channel).

    The relocated body changed only the ``finally`` block: it now emits
    ``self.finished.emit()`` (the worker's own ``Signal``) instead of
    ``self._shell.sig_preview_mode_finished.emit()``. The golden harness
    captures ``sig_message`` / ``sig_progress_update`` emissions (not
    ``finished``), so the fixture is byte-identical to the pre-migration
    version — the threading-vehicle change did not alter the
    ``sig_message``/``sig_progress_update`` sequence.

    ``preview_mode_started`` is ``False`` so the while loop is skipped —
    the scenario exercises the arm → start_lasers → stop_lasers → disarm
    path deterministically without entering the frame-grab loop.
    """
    import threading

    camera = MockCamera()
    siggen = MockSigGen(camera)
    motors = MockMotors()
    etls = MockETLs()
    lasers = (
        MockLaser(wavelength=555, max_power_mw=300.0, label="Laser 1 (555 nm)"),
        MockLaser(wavelength=647, max_power_mw=150.0, label="Laser 2 (647 nm)"),
    )
    bundle = DeviceBundle(
        camera=camera, siggen=siggen, motors=motors, etls=etls, lasers=lasers
    )

    shell = Mock()
    shell.ui.doubleSpinBox_cameraExposureTime.value.return_value = 100
    shell.preview_mode_started = False  # skip the frame-grab loop
    shell.estop_event = threading.Event()
    # Auto-laser flags + staged power — start_lasers/stop_lasers read these.
    shell._auto_laser1 = True
    shell._auto_laser2 = True
    shell.laser1_power_pct = 50.0
    shell.laser2_power_pct = 50.0
    shell._fs = Mock()
    shell.sig_message = Mock()
    shell.sig_progress_update = Mock()
    shell.sig_preview_mode_finished = Mock()

    hw = HardwareManager(bundle, shell)

    standin = Mock()
    standin.camera = camera
    standin._hw = hw
    standin._shell = shell
    # PreviewWorker.__init__ pre-samples the exposure time and receives the
    # frozen spawn MicroscopeSnapshot on the GUI thread; the golden harness
    # execs only run(), so set both here. The snapshot mirrors the
    # production spawn path: the shell's auto-laser flags and staged power
    # are folded into the frozen input the worker reads.
    from lightsheet.state.types import MicroscopeSnapshot

    standin._snapshot = MicroscopeSnapshot(
        lightsheet_line_time_s=1.0,
        laser_power_pct=(shell.laser1_power_pct, shell.laser2_power_pct),
        auto_lasers=(shell._auto_laser1, shell._auto_laser2),
    )
    standin._camera_exposure_time = 100
    return standin


# ---------------------------------------------------------------------------
# Ordered-call recording helpers (stack + manifest captures)
# ---------------------------------------------------------------------------


def _json_safe_arg(value: Any) -> Any:
    """Normalize a captured call argument to a JSON-safe deterministic value."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, np.ndarray):
        return f"<ndarray shape={tuple(value.shape)} dtype={value.dtype}>"
    if isinstance(value, (list, tuple)):
        return [_json_safe_arg(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _json_safe_arg(v) for k, v in value.items()}
    return f"<{type(value).__name__}>"


def _call_recorder(
    calls: list[dict],  # ty: ignore[missing-type-argument]
    name: str,
    fn: Callable[..., Any] | None = None,
) -> Callable[..., Any]:
    """Return a callable that appends a ``call`` entry to ``calls`` and
    then invokes ``fn`` (when given) so the real behavior still runs."""

    def _rec(*args: Any, **kwargs: Any) -> Any:
        calls.append(
            {
                "type": "call",
                "name": name,
                "args": [_json_safe_arg(a) for a in args],
                "kwargs": {
                    str(k): _json_safe_arg(v) for k, v in kwargs.items()
                },
            }
        )
        if fn is not None:
            return fn(*args, **kwargs)
        return None

    return _rec


def _emit_recorder(calls: list[dict], sig_name: str) -> Callable[..., Any]:  # ty: ignore[missing-type-argument]
    """Return an ``emit`` replacement recording the first positional arg."""

    def _rec(*args: Any, **kwargs: Any) -> None:
        calls.append(
            {
                "type": sig_name,
                "value": _json_safe_arg(args[0]) if args else None,
            }
        )

    return _rec


def _wrap_call(
    calls: list[dict],  # ty: ignore[missing-type-argument]
    obj: Any,
    attr: str,
    name: str | None = None,
) -> None:
    """Shadow ``obj.attr`` with a recording wrapper that calls through to
    the real implementation (instance-attribute shadowing — the class is
    untouched)."""
    orig = getattr(obj, attr)
    setattr(obj, attr, _call_recorder(calls, name or attr, orig))


# ---------------------------------------------------------------------------
# StackWorker.run() emission/teardown capture
# ---------------------------------------------------------------------------


def _build_stack_standin(scenario: str) -> Mock:
    """Build the Mock stand-in ``self`` for ``StackWorker.run``.

    Same self-is-the-worker shape as ``_build_preview_standin``: HAL
    attributes are the six ``Mock*`` classes and ``self._hw`` is a real
    ``HardwareManager`` over a mock ``DeviceBundle`` so the
    start/stop/select laser calls exercise real HardwareManager code.
    ``self._shell`` is a Mock carrying the shell-owned state ``run()``
    reads; ``saving_allowed`` is True so the teardown actually reaches
    ``_fs.stop_saving(lifecycle=...)`` — the fixture's pinned cleanup
    ordering — while ``_fs`` itself is a Mock so no filesystem is
    touched.

    Every ``StackWorker`` method is bound onto the stand-in from the
    real class via ``types.MethodType`` — enumerating the class rather
    than a hand-picked list keeps the harness correct across the planned
    in-file ``run()`` split: a future ``self._run_setup()`` /
    ``_run_plane_loop()`` / ``_run_teardown()`` call resolves to the real
    body here instead of being silently swallowed by a Mock auto-attr.
    """
    from lightsheet.state.types import MicroscopeSnapshot

    calls: list[dict] = []  # ty: ignore[missing-type-argument]

    camera = MockCamera()
    siggen = MockSigGen(camera)
    siggen.compute_scan_waveforms()
    motors = MockMotors()
    etls = MockETLs()
    lasers = (
        MockLaser(wavelength=555, max_power_mw=300.0, label="Laser 1 (555 nm)"),
        MockLaser(wavelength=647, max_power_mw=150.0, label="Laser 2 (647 nm)"),
    )
    bundle = DeviceBundle(
        camera=camera, siggen=siggen, motors=motors, etls=etls, lasers=lasers
    )

    shell = Mock()
    shell.saving_allowed = True
    shell.stack_mode_started = True
    shell.estop_event = threading.Event()
    shell.pause_requested = threading.Event()
    shell.number_of_planes = 3
    shell.save_filepath = "stack_save"
    shell.stack_starting_plane = 0.0
    shell.stack_step = 10000.0
    shell._laser_watchdog = None
    shell.reconstructed_frame = np.zeros((4, 4), dtype=np.uint16)
    shell.buffer = np.zeros((4, 4, 4), dtype=np.uint16)
    shell.reconstructed_frames = {}

    # Signal Mocks — emit calls append to the shared ordered call list.
    for sig_name in (
        "sig_message",
        "sig_progress_update",
        "sig_beep",
        "sig_refresh_position_horizontal",
        "sig_refresh_position_camera",
    ):
        sig = Mock()
        sig.emit.side_effect = _emit_recorder(calls, sig_name)
        setattr(shell, sig_name, sig)

    # The save side is a Mock — the fixture pins WHICH calls run() makes
    # (and their order), not the save internals (covered by the manifest
    # capture and the coordinator tests).
    fs = Mock()
    for meth in (
        "reinit",
        "add_sample_name",
        "set_files",
        "start_saving",
        "configure_adaptive",
        "configure_focus",
        "add_motor_parameters",
        "enqueue_buffer",
        "record_focus_sample",
        "stop_saving",
    ):
        getattr(fs, meth).side_effect = _call_recorder(calls, f"fs.{meth}")
    fs.manifest_update_queue = Mock()
    fs.manifest_update_queue.put_nowait.side_effect = _call_recorder(
        calls, "fs.manifest_update_queue.put_nowait"
    )
    shell._fs = fs

    # The pause-event clear in teardown is part of the pinned ordering —
    # wrap it on the instance so the record lands after finished.emit.
    _real_pause_clear = shell.pause_requested.clear
    shell.pause_requested.clear = _call_recorder(  # ty: ignore[invalid-assignment]
        calls, "pause_requested.clear", _real_pause_clear
    )

    hw = HardwareManager(bundle, shell)

    standin = Mock()
    standin.camera = camera
    standin.siggen = siggen
    standin.motors = motors
    standin.etls = etls
    standin.lasers = list(lasers)
    standin._hw = hw
    standin._shell = shell

    # Worker ctor attrs — the pre-sampled values __init__ would have set.
    standin._save_description = "sample"
    standin._save_stitch_blend = False
    standin._save_all_crop = False
    standin._save_all_full = False
    standin._multi_channel = False
    standin._start_plane = 0
    standin._run_completed = False
    standin._resume_manifest = None
    standin._wavelengths = [647]
    standin._adaptive_cfg = None
    standin._adaptive_controller = None
    standin._adaptive_current_cmd = None
    standin._focus_cfg = None
    standin._focus_controller = None
    standin._focus_block_count = 0
    standin._focus_curve = None
    standin._autofocus_cfg = None
    standin._autofocus_controller = None
    standin._autofocus_curve = None
    standin._snapshot = MicroscopeSnapshot(
        lightsheet_line_time_s=1.0,
        laser_power_pct=(50.0, 50.0),
        auto_lasers=(False, True),
    )

    # Record the HAL-touching calls so the setup/teardown ordering is in
    # the same ordered list as the signal emissions.
    _wrap_call(calls, camera, "arm_scan", "camera.arm_scan")
    _wrap_call(calls, camera, "disarm", "camera.disarm")
    _wrap_call(calls, siggen, "compute_scan_waveforms", "siggen.compute_scan_waveforms")
    _wrap_call(calls, siggen, "update_etls", "siggen.update_etls")
    _wrap_call(calls, motors, "get_positions", "motors.get_positions")
    _wrap_call(calls, motors, "move_axes_parallel", "motors.move_axes_parallel")
    _wrap_call(
        calls,
        motors.horizontal,
        "move_absolute_position",
        "motors.horizontal.move_absolute_position",
    )
    _wrap_call(calls, hw, "start_lasers", "hw.start_lasers")
    _wrap_call(calls, hw, "stop_lasers", "hw.stop_lasers")
    _wrap_call(calls, hw, "select_laser", "hw.select_laser")

    # Worker-side signals (finished + the trajectory/status signals).
    standin.finished = Mock()
    standin.finished.emit.side_effect = _call_recorder(calls, "finished.emit")
    for sig_name in (
        "sig_adaptive_trajectory",
        "sig_focus_trajectory",
        "sig_autofocus_status",
        "sig_applied_state",
    ):
        sig = Mock()
        sig.emit.side_effect = _emit_recorder(calls, sig_name)
        setattr(standin, sig_name, sig)

    # Bind EVERY real StackWorker method (incl. mixin members) onto the
    # stand-in so no self.-routed call can be swallowed by a Mock
    # auto-attr — this is what keeps the fixture honest across the
    # planned in-file run() split.
    for name, member in inspect.getmembers(
        StackWorker, predicate=inspect.isfunction
    ):
        if name.startswith("__") and name.endswith("__"):
            # Mock forbids magic-method attribute sets, and run() never
            # dispatches to one through self. anyway.
            continue
        setattr(
            standin,
            name,
            _call_recorder(calls, name, types.MethodType(member, standin)),
        )

    # The two deliberate overrides: acquire_scan is a Mock returning True
    # (it has its own golden coverage — this capture pins run()'s
    # skeleton, not the scan internals), and run is the exec'd body the
    # harness drives.
    standin.acquire_scan = _call_recorder(calls, "acquire_scan", lambda: True)
    run_fn = _load_method(
        "run(self) -> None",
        src_path=str(_STACK_SRC),
        extra_ns=dict(vars(_stack_mod)),
    )
    standin.run = _call_recorder(
        calls, "run", types.MethodType(run_fn, standin)
    )

    standin._calls = calls
    return standin


def capture_stack_sequence(scenario: str) -> list[dict]:  # ty: ignore[missing-type-argument]
    """Run the real ``StackWorker.run`` body against a Mock stand-in and
    return the ordered emission/teardown call list.

    Scenarios:

    * ``stack_completed`` — happy path, 3 planes: progress reset, the
      per-plane move/acquire/enqueue/progress sequence, the
      ``_run_completed`` path to ``stop_saving(lifecycle="completed")``,
      then the ETL/laser/disarm/finished teardown order.
    * ``stack_estop`` — ``estop_event`` set before run: the pre-stop
      guard skips ``start_lasers``, the first loop-top poll breaks with
      "Stack Acquisition Interrupted", teardown records
      ``lifecycle="interrupted"``.
    * ``stack_paused`` — ``pause_requested`` set before run: the
      loop-top pause poll breaks with "Stack Acquisition Paused",
      teardown records ``lifecycle="paused"`` and clears the pause
      event last.
    """
    if scenario not in ("stack_completed", "stack_estop", "stack_paused"):
        raise ValueError(f"unknown stack scenario: {scenario!r}")
    standin = _build_stack_standin(scenario)
    if scenario == "stack_estop":
        standin._shell.estop_event.set()
    elif scenario == "stack_paused":
        standin._shell.pause_requested.set()
    standin.run()
    return standin._calls


# ---------------------------------------------------------------------------
# Resume-manifest lifecycle capture (drives the real FrameSaver — no exec)
# ---------------------------------------------------------------------------


class _ManifestShell(QObject):
    """Minimal ``QObject`` shell stand-in for the real ``FrameSaver``.

    ``FrameSaver`` is a ``QObject`` that parents itself to the shell and
    connects ``sig_status_message`` to ``updateUi_message_printer``, so
    the stand-in must be a real ``QObject`` — a bare Mock cannot be a
    QObject parent.
    """

    def __init__(self, save_directory: str) -> None:
        super().__init__()
        self.save_format = "hdf5"
        self.save_directory = save_directory
        self.save_filepath = str(Path(save_directory) / "stack_save")
        self.estop_event = threading.Event()
        self.motors = MockMotors()
        self.stack_starting_plane = 0.0
        self.stack_ending_plane = 20000.0
        self.stack_step = 10000.0
        self.messages: list[str] = []

    def updateUi_message_printer(self, message: str) -> None:
        self.messages.append(message)


def _normalize_manifest(d: dict[str, Any]) -> dict[str, Any]:
    """Strip nondeterministic fields from a manifest dict so the fixture
    is stable: UUIDs, timestamps, absolute paths, and the safety-config
    fingerprint (whose content depends on the machine's config overlay)."""
    out = dict(d)
    if out.get("uuid"):
        out["uuid"] = "<UUID>"
    if out.get("created_at"):
        out["created_at"] = "<TS>"
    if out.get("completed_at"):
        out["completed_at"] = "<TS>"
    if out.get("save_filepath"):
        out["save_filepath"] = Path(out["save_filepath"]).name
    if out.get("safety_config"):
        out["safety_config"] = "<normalized>"
    cursors = out.get("cursors") or {}
    out["cursors"] = {
        fmt: {Path(k).name: v for k, v in group.items()}
        for fmt, group in cursors.items()
    }
    return out


def _snapshot_manifest(saver: FrameSaver, step: str) -> dict[str, Any]:
    """Read the on-disk sidecar JSON and return a normalized step record."""
    path = saver._manifest_path
    data: dict[str, Any] = {}
    if path is not None and Path(path).is_file():
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    norm = _normalize_manifest(data)
    return {
        "step": step,
        "state": norm.get("state"),
        "cursors": norm.get("cursors"),
        "manifest": norm,
    }


def capture_manifest_lifecycle(scenario: str) -> list[dict]:  # ty: ignore[missing-type-argument]
    """Drive the real ``FrameSaver`` manifest lifecycle and record the
    on-disk sidecar after each step.

    The capture calls the same public/underscored surface the save
    workers and ``stop_saving`` use (``set_files`` ->
    ``manifest_update_queue.put`` -> ``_drain_manifest_updates`` ->
    ``_commit_manifest_cursor`` -> ``stop_saving`` -> ``_finalize_manifest``),
    so it replays unchanged whether those bodies live on ``FrameSaver``
    or on an extracted collaborator behind delegate methods.
    """
    if scenario != "manifest_lifecycle":
        raise ValueError(f"unknown manifest scenario: {scenario!r}")
    steps: list[dict] = []  # ty: ignore[missing-type-argument]
    with tempfile.TemporaryDirectory() as td:
        shell = _ManifestShell(td)
        saver = FrameSaver(shell)  # ty: ignore[invalid-argument-type]

        # 1. set_files mints the acquisition UUID and writes the initial
        # sidecar with state="in_progress".
        saver.set_files(
            1, "stack_save", "stack", 3, "reconstructed_frame", wavelengths=[647]
        )
        steps.append(_snapshot_manifest(saver, "set_files"))

        # 2. Updates staged on the cross-thread queue apply to the
        # in-memory manifest on drain but are NOT persisted by the drain
        # alone — the on-disk snapshot must still show the pre-drain
        # state (the save worker is the sole writer contract).
        saver.manifest_update_queue.put(
            ManifestUpdate(
                kind="motor_position",
                payload={"horizontal position": 1.5},
            )
        )
        saver.manifest_update_queue.put(
            ManifestUpdate(
                kind="cursor",
                payload={
                    "format": "hdf5",
                    "key": saver.filenames_list[0],
                    "value": 1,
                },
            )
        )
        saver._drain_manifest_updates()
        steps.append(_snapshot_manifest(saver, "drain_updates"))

        # 3. A durable cursor commit drains staged updates, applies its
        # own cursor, and writes the sidecar.
        saver._commit_manifest_cursor("hdf5", saver.filenames_list[0], 2)
        steps.append(_snapshot_manifest(saver, "commit_cursor"))

        # 4. stop_saving stages the final motor positions + lifecycle,
        # flips saving_started, and (no worker thread here) the post-join
        # _finalize_manifest drains and writes the terminal state.
        saver.stop_saving(lifecycle="completed")
        steps.append(_snapshot_manifest(saver, "stop_saving_completed"))
    return steps


def capture_acquisition_sequence(scenario: str) -> list[dict]:  # ty: ignore[missing-type-argument]
    """Run the real acquire_scan body against a Mock stand-in and return
    the ordered ``sig_message`` / ``sig_progress_update`` emit sequence.

    ``scenario`` selects the fixture:

    * ``"default"`` — the silent happy path (no DAQ error, no camera
      timeout). Emits zero ``sig_message`` / ``sig_progress_update`` calls;
      the fixture is an empty list. This characterizes the contract: a
      successful acquisition is silent on the message channel.
    * ``"siggen_create_scanner_fail"`` — the siggen ``create_scanner``
      failure early-return path. The stand-in's ``create_scanner`` is
      patched to set ``siggen.error = 1`` +
      ``siggen.error_message = "create_scan error"`` (mirroring the real
      ``SigGen.create_scanner`` bare-except branch), so ``acquire_scan``
      hits its ``if self.siggen.error:`` early-return and emits the
      "Scan task creation failed" ``sig_message``. This closes one error
      path: a dropped or re-sequenced emission on the
      create-scanner failure branch is now catchable, not just the happy
      path.
    * ``"preview_auto_laser"`` — the D-05 preview-auto-laser fold. Runs
      ``preview_mode_worker`` (not ``acquire_scan``) against a stand-in
      whose ``self._hw`` is a real ``HardwareManager`` backed by Mock
      devices. The D-05 fold inserted ``self._hw.start_lasers()`` after
      ``camera.arm()`` and ``self._hw.stop_lasers()`` before
      ``camera.disarm()``; on the happy path (MockLaser, no HAL error)
      the ``sig_message`` sequence is empty — the fold introduced no
      stray emission on the message channel. This is the ONE scenario
      expected to differ from a hypothetical pre-split re-recording:
      before the fold, ``preview_mode_worker`` did not call
      ``start_lasers``/``stop_lasers`` at all; now it does, and a future
      change that makes the preview path emit on the happy path (or
      re-sequences the laser calls relative to arm/disarm) is caught
      here.

    The sequence is a list of ``{"type": "sig_message" |
    "sig_progress", "value": <first positional arg>}`` dicts in emission
    order.
    """
    if scenario in ("stack_completed", "stack_estop", "stack_paused"):
        return capture_stack_sequence(scenario)
    if scenario == "manifest_lifecycle":
        return capture_manifest_lifecycle(scenario)
    if scenario not in ("default", "siggen_create_scanner_fail", "preview_auto_laser"):
        raise ValueError(f"unknown scenario: {scenario!r}")

    if scenario == "preview_auto_laser":
        standin = _build_preview_standin()
        worker = _load_method("run(self) -> None", src_path=_PREVIEW_LIVE_SINGLE_SRC)  # ty: ignore[invalid-argument-type]
        worker(standin)
        sequence: list[dict] = []  # ty: ignore[missing-type-argument]
        for call in standin._shell.sig_message.emit.call_args_list:
            sequence.append({"type": "sig_message", "value": call.args[0]})
        for call in standin._shell.sig_progress_update.emit.call_args_list:
            sequence.append({"type": "sig_progress", "value": call.args[0]})
        return sequence

    standin = _build_standin()
    if scenario == "siggen_create_scanner_fail":
        # Mirror the real SigGen.create_scanner bare-except branch: it sets
        # error=1 + a generic 'create_scan error' message and never raises.
        # acquire_scan resets self.siggen.error = 0 before the call, then
        # checks it after — so the failure must be set inside create_scanner.
        def _fail_create_scanner() -> None:
            standin.siggen.error = 1
            standin.siggen.error_message = "create_scan error"

        standin.siggen.create_scanner = _fail_create_scanner
    acquire_scan = _load_method("acquire_scan(self) -> bool", src_path=_SCAN_MIXIN_SRC)  # ty: ignore[invalid-argument-type]
    acquire_scan(standin)

    sequence = []
    for call in standin._shell.sig_message.emit.call_args_list:
        sequence.append({"type": "sig_message", "value": call.args[0]})
    for call in standin._shell.sig_progress_update.emit.call_args_list:
        sequence.append({"type": "sig_progress", "value": call.args[0]})
    return sequence


def record_acquisition(out_path: str, scenario: str = "default") -> None:
    """Capture a scenario and write it to ``out_path`` as JSON."""
    seq = capture_acquisition_sequence(scenario)
    with Path(out_path).open("w", encoding="utf-8") as f:
        json.dump(seq, f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    base = Path(__file__).resolve().parent
    scenarios = {
        "default": base / "default.json",
        "siggen_create_scanner_fail": base / "siggen_create_scanner_fail.json",
        "preview_auto_laser": base / "preview_auto_laser.json",
        "stack_completed": base / "stack_completed.json",
        "stack_estop": base / "stack_estop.json",
        "stack_paused": base / "stack_paused.json",
        "manifest_lifecycle": base / "manifest_lifecycle.json",
    }
    for name, path in scenarios.items():
        record_acquisition(str(path), name)
        print(f"Wrote {path}")
