"""Golden-master capture harness for the acquire_scan signal sequence.

This module is the SOLE regeneration path for ``test/golden/default.json``
(D-12). The fixture is generated by running::

    uv run python test/golden/_record.py

and is committed to the repo. It must NOT be hand-edited — a hand-edit
would mask the exact regression this safety net exists to catch. The
replay test ``test/test_golden_acquisition.py`` asserts
``capture_acquisition_sequence("default") == json.load(default.json)``;
regenerating the fixture after a refactor produces a diff that is the
behavioral change to review.

Determinism sources (EDGE — flagged-unverified assumption, documented here
so the safety net's integrity is auditable):

* ``MockSigGen`` reuses the pure-numpy ``lightsheet.waveforms`` generators
  with hardcoded synthetic config defaults (sample_rate=40000, etc.) — no
  config.ini read, no hardware, no random seed. The same inputs always
  produce bit-identical waveform arrays.
* ``MockCamera`` returns ``np.zeros((n, ysize, xsize), dtype=uint16)``
  canned frames — deterministic shape and content.
* ``MockMotors`` / ``MockETLs`` / ``MockLaser`` track state in plain
  instance attributes with no I/O.

The harness execs the REAL ``Controller_MainWindow.acquire_scan`` body
(via the ``_load_method`` exec-against-Mock pattern from
``test/test_laser_controls.py``) against a Mock stand-in ``self`` whose
HAL attributes are the six ``Mock*`` classes. This runs the real method
source — the same code that runs on the rig — without needing a Qt event
loop or a display (RESEARCH.md §Standard Stack: no pytest-qt). The
ordered ``sig_message.emit`` / ``sig_progress_update.emit`` call sequence
is captured as a JSON list of ``{"type": ..., "value": ...}`` dicts.

``acquire_scan`` references module-level names (``datetime``, ``logger``,
``np``) from ``lightsheet/gui/controller.py``; the exec namespace is
seeded with them so the body resolves them at call time.
"""

import datetime
import json
import logging
import os
import re
from collections.abc import Callable
from typing import Any
from unittest.mock import Mock

import numpy as np

from lightsheet.hal import (
    MockCamera,
    MockETLs,
    MockLaser,
    MockMotors,
    MockSigGen,
)

_CONTROLLER_SRC = os.path.join(
    os.path.dirname(__file__), "..", "..", "lightsheet", "gui", "controller.py"
)
_ACQ_SRC = os.path.join(
    os.path.dirname(__file__), "..", "..", "lightsheet", "gui", "acquisition_coordinator.py"
)

# Module-level logger the exec'd body references (controller.py:45).
_logger = logging.getLogger("lightsheet.gui.controller")


def _read_controller_source() -> str:
    with open(_CONTROLLER_SRC) as f:
        return f.read()


def _slice_method(src: str, method_sig: str) -> str:
    """Return the body of a method, from its ``def <sig>:`` line up to the
    next top-level ``def``/``@pyqtSlot`` decorator."""
    m = re.search(r"def " + re.escape(method_sig) + r":", src)
    assert m, f"{method_sig} is missing"
    body = src[m.start() :]
    end = re.search(r"\n    def |\n    @pyqtSlot", body[1:])
    if end:
        body = body[: end.start() + 1]
    return body


def _load_method(method_sig: str, src_path: str = _CONTROLLER_SRC) -> Callable[..., Any]:
    """Extract a method body from the given source file and return a callable.

    Defaults to controller.py; pass ``_ACQ_SRC`` for ``acquire_scan`` (moved
    to ``AcquisitionCoordinator`` in the god-object split). The exec
    namespace is seeded with the module-level names the body references
    (``datetime``, ``logger``, ``np``) so the function resolves them at
    call time via its ``__globals__``.
    """
    with open(src_path) as f:
        src = f.read()
    body = _slice_method(src, method_sig)
    namespace: dict[str, Any] = {
        "datetime": datetime,
        "logger": _logger,
        "np": np,
    }
    exec(compile(body, src_path, "exec"), namespace)
    func_name = method_sig.split("(")[0].strip()
    return namespace[func_name]


def _build_standin() -> Mock:
    """Build the Mock stand-in ``self`` for acquire_scan.

    acquire_scan now lives on ``AcquisitionCoordinator`` (god-object split).
    The coordinator reads its own ``self.camera`` / ``self.siggen`` /
    ``self.motors`` attributes and shell-owned state via ``self._shell.*``
    (``sig_message``, ``sig_progress_update``, ``ui.*`` widgets, ``_fs``,
    ``buffer`` / ``reconstructed_frame`` / ``buffer_metadata_*``,
    ``reconstruct_frame`` / ``reconstruct_frame_linear_blend``). The
    stand-in mirrors that shape: it IS the coordinator (``self``), with
    ``self._shell`` a Mock exposing the shell-owned attributes acquire_scan
    reads. The siggen's waveforms are pre-computed so ``waveform_cycles`` /
    ``waveform_metadata`` are populated (the real coordinator calls
    ``compute_scan_waveforms`` before ``acquire_scan``).
    """
    camera = MockCamera()
    siggen = MockSigGen(camera)
    siggen.compute_scan_waveforms()

    standin = Mock()
    # Coordinator's own HAL handles.
    standin.camera = camera
    standin.siggen = siggen
    standin.motors = MockMotors()
    # The coordinator holds list[ILaser] (Wave 3 rewrite). acquire_scan does
    # not reference self.lasers, but the stand-in mirrors hardware_init's
    # shape so a future body change that does read laser state is caught.
    standin.lasers = [
        MockLaser(wavelength=555, max_power_mw=300.0, label="Laser 1 (555 nm)"),
        MockLaser(wavelength=640, max_power_mw=150.0, label="Laser 2 (640 nm)"),
    ]
    standin.etls = MockETLs()

    # Shell reference — acquire_scan reads shell-owned state via self._shell.*
    shell = Mock()
    # Signal mocks — emit calls are captured via call_args_list.
    shell.sig_message = Mock()
    shell.sig_progress_update = Mock()
    # UI widgets acquire_scan reads via self._shell.ui.* (Pitfall 7 — the
    # ONE tolerated cross-tier read this phase).
    shell.ui.lineEdit_saveDescription.text.return_value = "sample"
    shell.ui.checkBox_saveStitchBlend.isChecked.return_value = False
    # FrameSaverController enqueue_frame receives the reconstructed frame.
    shell._fs = Mock()
    # Frame-reconstruction helpers stay on the shell — acquire_scan calls
    # self._shell.reconstruct_frame(self._shell.buffer). Plain Mock
    # callables return Mock instances; the enqueue_frame capture is what
    # the golden replay asserts on (the emission sequence), not the frame
    # content.
    standin._shell = shell

    return standin


def capture_acquisition_sequence(scenario: str) -> list[dict]:
    """Run the real acquire_scan body against a Mock stand-in and return
    the ordered ``sig_message`` / ``sig_progress_update`` emit sequence.

    ``scenario`` selects the fixture:

    * ``"default"`` — the silent happy path (no DAQ error, no camera
      timeout). Emits zero ``sig_message`` / ``sig_progress_update`` calls;
      the fixture is an empty list. This characterizes the contract: a
      successful acquisition is silent on the message channel.
    * ``"siggen_create_scanner_fail"`` — the siggen ``create_scanner``
      failure early-return path. The stand-in's ``create_scanner`` is
      patched to set ``siggen.error = 1`` +
      ``siggen.error_message = "create_scan error"`` (mirroring the real
      ``SigGen.create_scanner`` bare-except branch), so ``acquire_scan``
      hits its ``if self.siggen.error:`` early-return and emits the
      "Scan task creation failed" ``sig_message``. This closes Pitfall 2
      for one error path: a dropped or re-sequenced emission on the
      create-scanner failure branch is now catchable, not just the happy
      path.

    The sequence is a list of ``{"type": "sig_message" |
    "sig_progress", "value": <first positional arg>}`` dicts in emission
    order.
    """
    if scenario not in ("default", "siggen_create_scanner_fail"):
        raise ValueError(f"unknown scenario: {scenario!r}")
    standin = _build_standin()
    if scenario == "siggen_create_scanner_fail":
        # Mirror the real SigGen.create_scanner bare-except branch: it sets
        # error=1 + a generic 'create_scan error' message and never raises.
        # acquire_scan resets self.siggen.error = 0 before the call, then
        # checks it after — so the failure must be set inside create_scanner.
        def _fail_create_scanner() -> None:
            standin.siggen.error = 1
            standin.siggen.error_message = "create_scan error"

        standin.siggen.create_scanner = _fail_create_scanner
    acquire_scan = _load_method("acquire_scan(self) -> None", src_path=_ACQ_SRC)
    acquire_scan(standin)

    sequence: list[dict] = []
    for call in standin._shell.sig_message.emit.call_args_list:
        sequence.append({"type": "sig_message", "value": call.args[0]})
    for call in standin._shell.sig_progress_update.emit.call_args_list:
        sequence.append({"type": "sig_progress", "value": call.args[0]})
    return sequence


def record_acquisition(out_path: str, scenario: str = "default") -> None:
    """Capture a scenario and write it to ``out_path`` as JSON."""
    seq = capture_acquisition_sequence(scenario)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(seq, f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    base = os.path.dirname(__file__)
    scenarios = {
        "default": os.path.join(base, "default.json"),
        "siggen_create_scanner_fail": os.path.join(
            base, "siggen_create_scanner_fail.json"
        ),
    }
    for name, path in scenarios.items():
        record_acquisition(path, name)
        print(f"Wrote {path}")
